### ISSUE TITLE
Connection Pop Up show Custodi instead of Custodia (Italian Translation)

### ISSUE THREAD

**Issue by giovanniro98** [ThePBone/GalaxyBudsClient#102]
Windows 10 64bit
The connection pop up show Custodi instead of Custodia in Italian.
Also is it possibile to include an image for the case (app and pop up)?

**Comment by ThePBone** [comment]
> The connection pop up show Custodi instead of Custodia in Italian.

Fixed with commit 0177b3d59f13859061dda1020892f271e72e5ddd. It is included with v4.0.2 that was just released.

> Also is it possible to include an image for the case (app and pop up)?

Yes, but there is not that much space for a case icon. Maybe I could replace that text label with a small case icon, but it would look a bit squished together. Also, I don't think Samsung created any line-art icons of the Buds Live/Pro cases, so I would need to use the "more realistic" looking icons that don't match this app's theme.

**Comment by giovanniro98** [comment]
Not fixed for me on 4.0.2, the correct form of case in italian is Custodia. On the app an pop up there is Custodi (an a is missing).

**Comment by ThePBone** [comment]
It looks like the actual string was correct, just the text label was too small so the 'a' was cut off. Fixed with e792431
