### ISSUE TITLE
[BUG] Linux - Cannot register profile. org.bluez.Error.NotPermitted: UUID already registered

### ISSUE THREAD

**Issue by F0xedb** [ThePBone/GalaxyBudsClient#337]
**Describe the bug**  
When launching the application on Arch Linux the earbuds are connecting and working as intended.
However, when disconnecting (Putting the buds in their case) and reconnecting I'm greated with an  `org.bluez.Error.NotPermitted: UUID already registered` error in the UI

**To Reproduce**  
1. Connect earbuds to the application
2. Put earbuds in the case (So they disconnect)
3. Take earbuds out of the case
4. Watch that reconnecting fails

PS: This is on linux with the bluez backend

**Expected behavior**  
When taking the earbuds out of the case the second time the earbuds should connect again to the application

**Desktop (please complete the following information):**  
 - OS: Arch Linux 64bit
 - Application version: 4.5.2-3 (Installed from AUR)

**Log files**  
```
12:45:36 INF] Using settings file at: /home/aether/.local/share/GalaxyBudsClient/config.json
[12:45:37 INF] SingleInstanceWatcher: Server listening at tcp:host=::1,port=54532
[12:45:38 DBG] BluetoothImpl: Using Linux.BluetoothService
[12:45:38 INF] Translator mode file location: /home/aether/.local/share/GalaxyBudsClient/custom_language.xaml
[12:45:38 INF] User script directory: /home/aether/.local/share/GalaxyBudsClient/scripts
[12:45:38 INF] ScriptManager: 0 user script(s) found
[12:45:38 DBG] MainWindow.Instance: Initializing window with default WindowImpl
[12:45:39 WRN] StubDeviceSpec: initialized
[12:45:39 DBG] FirmwareRemoteClient: Searching for firmware binaries...
GalaxyBudsClient Warning: 0 : Attribute 'stroke-dasharray' cannot be set - type 'Svg.SvgPath' cannot convert from string 'null'.
GalaxyBudsClient Warning: 0 : Attribute 'stroke-width' cannot be set - type 'Svg.SvgPath' cannot convert from string 'null'.
[12:45:39 WRN] StubDeviceSpec: initialized
[12:45:39 DBG] Linux.BluetoothService: No adapter preselected. Choosing default one.
[12:45:39 DBG] Linux.BluetoothService: Using Bluetooth adapter: hci0
[12:45:39 DBG] Linux.BluetoothService: Connecting... (attempt 1/5)
[12:45:39 DBG] Linux.BluetoothService: Device ready. Registering profile client for UUID 00001101-0000-1000-8000-00805f9b34fb...
[12:45:39 DBG] Linux.BluetoothService: Connecting to profile... (attempt 1/10)
[12:45:39 WRN] Dummy.HotkeyReceiver: Platform not supported
[12:45:40 DBG] Linux.BluetoothService: Using Bluetooth adapter: hci0
[12:45:40 DBG] Linux.BluetoothSocket: Connected to profile
[12:45:40 DBG] Linux.BluetoothService: Connection established. Launching BluetoothServiceLoop.
[12:45:40 DBG] FirmwareRemoteClient: 0 firmware found.
[12:45:41 DBG] SpatialAudioDataParser: Unknown id (38)
[12:45:41 DBG] SpatialAudioDataParser: Unknown id (38)
[12:45:41 WRN] NoiseControlSwitchMode: Unknown mode
[12:45:43 WRN] NoiseControlSwitchMode: Unknown mode
[12:45:43 WRN] NoiseControlSwitchMode: Unknown mode
[12:45:44 WRN] NoiseControlSwitchMode: Unknown mode
[12:45:45 DBG] ExperimentClient: Scanning for experiments...
[12:45:45 WRN] NoiseControlSwitchMode: Unknown mode
[12:45:45 DBG] ExperimentClient: 0 experiment(s) found.
[12:45:50 DBG] Linux.BluetoothService: Disconnected
[12:45:51 ERR] Linux.BluetoothService: BluetoothServiceLoop: UnixException thrown while handling unsafe stream: Error 104: Connection reset by peer. Cancelled.
[12:45:57 DBG] Linux.BluetoothService: Reconnected. Attempting to auto-connect to profile...
[12:45:57 DBG] Linux.BluetoothService: Connecting... (attempt 1/5)
[12:46:07 DBG] Linux.BluetoothService: Device ready. Registering profile client for UUID 00001101-0000-1000-8000-00805f9b34fb...
[12:46:07 ERR] Linux.BluetoothService: Cannot register profile. org.bluez.Error.NotPermitted: UUID already registered
[12:46:32 INF] MainWindow.TitleBar: Close requested, minimizing to tray bar
```
The error happens in the last 4 lines (When trying to reconnect)

**Comment by ThePBone** [comment]
Thanks for reporting this issue. 

Commit f8bc12ca21b9aca0b3997a4690474a8fc36b6a24 should fix this issue.

You can grab precompiled binaries here: https://github.com/ThePBone/GalaxyBudsClient/actions/runs/2504471891

**Comment by SayantanRC** [comment]
@ThePBone the issue is still present. I am on Linux mint 21 (based on ubuntu 22). How do I get the log files to report?

**Comment by 30p87** [comment]
Had the same error (Arch) (Kernel 6.1.6-arch1-3 and prior). Disabling minize to tray, therefore forcing it to always completely reopen and reconnect, seems to fix it.

**Comment by scaryvoid** [comment]
30p87's suggestion worked for me. Thanks!
